version: '3'
services:
  demo:
    build: .
    container_name: deploy-python-demo
  nginx:
    image: nginx:mainline
    ports:
      - "80:80"
    volumes:
      - ./deploy-python.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - demo
    container_name: deploy-python-nginx
    restart: always
    
    