version: '3'

services:
  nginx:
    image: nginx:mainline
    ports:
      - "80:80"
    volumes:
      - ./deploy-maven.conf:/etc/nginx/conf.d/deploy-maven.conf
    depends_on:
      - app
    restart: always
    container_name: deploy-maven-nginx

  app:
    build: .
    container_name: deploy-maven-app
    restart: always